#Tweaks
[tweaks]
	#0 = disable buttons (i.e. keybind only)
	#1 = buttons for player sorting only
	#2 = buttons for external sorting only
	#3 = all buttons enabled (default)
	#Range: 0 ~ 3
	enableButtons = 1
	#Enable auto-refill
	autoRefill = true
	#0 = disable sorting
	#1 = player sorting only
	#2 = external sorting only
	#3 = all sorting enabled (default)
	#Range: 0 ~ 3
	enableSort = 3
	#Enable a quick view of how many items that you're currently holding exists in your inventory by displaying it next your hotbar.
	quickView = true
